/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import model.entities.Cliente;
import persistence.dao.ClienteDAO;

/**
 *
 * @author dener
 */
public class ListarClientesView extends javax.swing.JPanel {
    private final MainView context; 
    private ClienteController clienteController;
    private ArrayList<Cliente> allClientes;
    
    private ArrayList<Cliente> clientesMostrados;
    private final DefaultListModel<String> clienteModel;
    
    /**
     * Creates new form ListarClientesView
     */
    public ListarClientesView(MainView context) {
        initComponents();
        this.context = context;
        
        this.clienteController = new ClienteController(new ClienteDAO());
        this.allClientes = clienteController.recuperarTodos();
        
        this.clienteModel = new DefaultListModel<>();
        this.clientes.setModel(clienteModel);
        
        this.clientesMostrados = (ArrayList<Cliente>) allClientes.clone();
        
        updateListaDeClientes();
    }
    
    private void updateListaDeClientes() {
        this.clienteModel.removeAllElements();
        for(Cliente c : this.clientesMostrados) {
            this.clienteModel.addElement(c.getNome() + " - " + c.getCpf());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        filtrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        adicionarEndereco = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listar Clientes");

        jLabel2.setText("Filtrar por nome:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        clientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(clientes);

        jLabel3.setText("Clientes:");

        filtrar.setText("Filtrar");
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.setActionCommand("editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        adicionarEndereco.setText("+ Endereço");
        adicionarEndereco.setActionCommand("addEndereco");
        adicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(adicionarEndereco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filtrar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(adicionarEndereco))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed

    }//GEN-LAST:event_nomeActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
        String nomeCliente = this.nome.getText();
        
        if(nomeCliente.length() == 0) {
            new AlertMessage("Listar Clientes", "Digite o nome do cliente");
            this.clientesMostrados = (ArrayList<Cliente>) allClientes.clone();
            updateListaDeClientes();
        } else {
            this.clientesMostrados.clear();
            for(Cliente c : allClientes) {
                if(c.getNome().equals(nomeCliente)) {
                    this.clientesMostrados.add(c);
                }
            }
            
            if(this.clientesMostrados.size() == 0) {
                this.clientesMostrados = (ArrayList<Cliente>) allClientes.clone();
                updateListaDeClientes();
                new AlertMessage("Listar Clientes", "Nenhum Cliente Encontrado");
            } else {
                updateListaDeClientes();
            }
        }
    }//GEN-LAST:event_filtrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if(this.clientes.getSelectedIndices().length != 1) {
            new AlertMessage("Listar Cliente", "Selecione 1 cliente para editar");
            return;
        }
        
        int index = this.clientes.getSelectedIndex();
        this.context.updateView(new EditarClienteView(this.context, this.clientesMostrados.get(index)));
    }//GEN-LAST:event_editarActionPerformed

    private void adicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEnderecoActionPerformed
        if(this.clientes.getSelectedIndices().length != 1) {
            new AlertMessage("Listar Cliente", "Selecione 1 cliente para adicionar endereço");
            return;
        }
        
        int index = this.clientes.getSelectedIndex();
        this.context.updateView(new CadastrarEnderecoView(this.context, this.clientesMostrados.get(index)));
    }//GEN-LAST:event_adicionarEnderecoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEndereco;
    private javax.swing.JList<String> clientes;
    private javax.swing.JButton editar;
    private javax.swing.JButton filtrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
